### ISSUE TITLE
戦闘時に出るエンチャント等の表記(翻訳）がおかしい

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#35]

**Comment by TAKA1210** [comment]
翻訳を一度見てみて、全体的に統一した表記にしたい

**Comment by snake0623** [comment]
オープンプロジェクト化に伴いほぼ全ての翻訳ファイルをオープンにしますので、Pull requestで編集が可能です。

Masterブランチへの翻訳ファイル反映は、来週中をめどにしています。

**Comment by snake0623** [comment]
翻訳ファイルのpushが行われていますので、fork後Pull Requestをしてください。
