### ISSUE TITLE
死んだ（死亡ログが出た）が死んでいないバグ

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#37]

**Comment by TAKA1210** [comment]
![2018-02-26_00 42 35](https://user-images.githubusercontent.com/26005599/36643408-2a2641b8-1a8e-11e8-8669-e33b1b5b9c44.png)

**Comment by snake0623** [comment]
死亡理由及び、死亡時に装着していた装備情報をいただければ幸いです。

@TAKA1210

**Comment by TAKA1210** [comment]
shot by skeleton

**Comment by snake0623** [comment]
恐らく修正
