### ISSUE TITLE
投票によるアイテムを受け取れない

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#51]
spawn付近にあるエンダーチェストを開いても何も表示されない

**Comment by snake0623** [comment]
権限やシステムによる不具合ではないことを確認しました。また、ミステリーボックス側のシステムを確認しましたが、特に再現ができませんでした。

投票が行われていないか、投票時にサーバの再起動のタイミングと重なりキャッシュが削除された可能性があります。
https://www.mcplay.biz/2018/03/update/fixed-vote-bonus/

引き続き問題が発生する場合は、issueを再度作成して下さい。
