### ISSUE TITLE
クリーパーが爆発すると、マイクラ自体がクラッシュする

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#52]
私の端末による原因かもしれないので確認を

**Comment by snake0623** [comment]
Minecraft 1.12.2 Optifine HD C6 Ultra環境下での問題再現が不可能でした。

ご使用のMinecraftバージョン及びクラッシュ時のレポートの添付を行った上で再度issueを開くようお願い致します。
