### ISSUE TITLE
投票のアイテムが受け取れない

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#54]
3日程度前からもんだいは発生している。3回とも時間帯はばらばらだし全部はねられる確率なんてあり得ない

**Comment by snake0623** [comment]
応急処置として、保存形式をデータベースからフラットファイルへ一時的に変更しました。
また、TAKA_1210に対しミステリーボックス３個を手動配布しました。
確認して頂ければ幸いです。

Closed
