### ISSUE TITLE
クリーパーに攻撃するとマイクラ自体がクラッシュする

### ISSUE THREAD

**Issue by TAKA1210** [GravittoGroup/SNAKENetWork#55]

**Comment by TAKA1210** [comment]
[crash-2018-03-27_00.11.44-client.txt](https://github.com/GravittoGroup/SNAKENetWork/files/1848408/crash-2018-03-27_00.11.44-client.txt)
[crash-2018-03-27_00.15.44-client.txt](https://github.com/GravittoGroup/SNAKENetWork/files/1848409/crash-2018-03-27_00.15.44-client.txt)

**Comment by TAKA1210** [comment]
推測ではあるが、この鯖におけるクリーパーは死ぬときに現在かかっているエフェクト効果を残留ポーションのようにまき散らす。追加エンチャプラグインによって相手に簡単にデバフを加えることができるので、武器に2つ以上のデバフ効果かがある場合、バグる可能背一がある(要検証）。

**Comment by TAKA1210** [comment]
以前まで（現在のようにいろいろテコ入れが入る前）まではそんなことがなかったので、新しく入れたかもしれないプラグインと競合しているか、設定が変わってしまったプラグインと競合しているか、私の端末側に問題がある

**Comment by TAKA1210** [comment]
デバフ付与効果による影響はないと考えられる。
デバフ付与のついていない武器で倒そうとしたときもマイクラはクラッシュした。
ただ、弓ではデバフ効果のあるなしにかかわらずクラッシュしなかった。

**Comment by TAKA1210** [comment]
[crash-2018-03-27_00.33.39-client.txt](https://github.com/GravittoGroup/SNAKENetWork/files/1848453/crash-2018-03-27_00.33.39-client.txt)

**Comment by snake0623** [comment]
運営側の環境では同様の問題を引き起こすことが不可能でした。
もしも、クライアントに導入しているMODがありましたら、ビルドバージョンまでの詳しい情報を追記お願い致します。
また、Forge Mod Loaderを導入している場合は、同問題発生タイミングのログも教えて頂ければ幸いです。

下記確認できたサーバログ
`[00:11:45] [Server thread/INFO]: TAKA_1210 lost connection: Disconnected`
```
00:11:45 [WARNING] [TAKA_1210] -> UpstreamBridge - NativeIoException: syscall:read(..) failed: Connection reset by peer
00:11:45 [INFO] [TAKA_1210] disconnected with: §fNativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
00:11:45 [INFO] [TAKA_1210] -> UpstreamBridge has disconnected
00:11:45 [INFO] [TAKA_1210] <-> DownstreamBridge <-> [survival-1] has disconnected
```
